language: python
python: '2.7'
install: pip install mkdocs

before_install:
- openssl aes-256-cbc -K $encrypted_ead4033b2154_key -iv $encrypted_ead4033b2154_iv
  -in deploy-key.enc -out deploy-key -d

script:
- chmod 600 deploy-key
- eval `ssh-agent -s`
- git config user.name "Automatic Publish"
- git config user.email "wj_mailbox163@163.com"
- cd wusewolf/mydocs && mkdocs build && git add site && git commit -m "update site"
- cd wusewolf/mydocs && git checkout gh-pages && git rebase master
