language: python
python: '2.7'
install: pip install mkdocs
before_install:
- openssl aes-256-cbc -K $encrypted_ead4033b2154_key -iv $encrypted_ead4033b2154_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config user.name "Automatic Publish"
- git config user.email "wj_mailbox163@163.com"
- git clone git@github.com:wusewolf/mydocs.git mydocs
script:
- cd "$TRAVIS_BUILD_DIR"/mydocs
- mkdocs build --clean
- mkdocs gh-deploy