site_name: My Docs
pages:
- Home: index.md
- Algorithm:
    - Search:
        - binany_search: algorithm/algorithm.md
        - order_search: algorithm/order_search.md
    - Sort: sort.md
    - Tree: tree.md
- C/C++: cc.md
- Mkdocs:
    - tips: mkdocs/usemkdocs.md
- About: about.md
